require 'rubygems'
gem 'hoe', '>= 2.1.0'
gem 'rspec', '>= 1.2.8'
require 'hoe'
require 'fileutils'

Hoe.plugin :newgem

# Generate all the Rake tasks
# Run 'rake -T' to see list of generated tasks (from gem root directory)
$hoe = Hoe.spec 'jstyler' do
  self.developer 'webdizz', 'webdizz@gmail.com'
  self.post_install_message = '
  Usage: 
     buildr format 
  For details go to http://webdizz.name/posts/jstyler.
  '
  self.rubyforge_name       = self.name # TODO this is default value
  self.extra_deps         = [['buildr','>= 1.3.5'], ['session','>=2.4.0']]

end
