require 'jstyler'

VERSION_NUMBER = '1.0'

jstyler.options[:convention] = 'java'
jstyler.options[:verbose] = true

define 'testable' do
	
	project.version = VERSION_NUMBER
  	project.group = 'name.webdizz.jstyler.testable'
	compile.options.target = '1.5'
	package :jar

end
